authors/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'authors'
urlpatterns = (
    path('', TemplateView.as_view(template_name='authors/list.html'), name='list'),
)

books/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'books'
urlpatterns = (
    path('', TemplateView.as_view(template_name='books/list.html'), name='list'),
)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('books/', include('books.urls')),
    path('authors/', include('authors.urls')),
    path('admin/', admin.site.urls),

    # api endpoints
    path('api/', include('authors.api')),
    path('api/', include('books.api'))
]

authors/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=250)
    age = models.PositiveIntegerField()

    def __str__(self):
        return self.name

books/models.py
from django.db import models

from authors.models import Author

GENRE = [
    (1, 'Fantasy'),
    (2, 'Science Fiction'),
    (3, 'Romance'),
    (4, 'Mystery'),
    (5, 'Dystopia')
]


class Book(models.Model):
    title = models.CharField(max_length=255)
    synopsis = models.TextField(blank=True)
    genre = models.SmallIntegerField(choices=GENRE)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, related_name='books'
    )
    created_by = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.title

authors/views.py
from rest_framework.viewsets import ModelViewSet
from django_filters import rest_framework as filters

from .models import Author
from .serializers import AuthorSerializer
from .filter import AuthorFilter


class AuthorViewset(ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_class = AuthorFilter

books/views.py
from rest_framework.viewsets import ModelViewSet
from django_filters import rest_framework as filters

from .models import Book
from .serializers import BookSerializer
from .filter import BookFilter


class BookViewset(ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_class = BookFilter

templates/authors/list.html
{% extends "index.html" %}
{% load render_bundle from webpack_loader %}


{% block content %}
  <div id="root"></div>
  {% render_bundle 'author' %}
{% endblock content %}

templates/books/list.html
{% extends "index.html" %}
{% load render_bundle from webpack_loader %}


{% block content %}
  <div id="root"></div>
  {% render_bundle 'book' %}
{% endblock content %}

templates/index.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Books</title>
</head>
<body>
  {% render_bundle 'main_css' %}

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Book</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authors:list' %}">Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:list' %}">Books</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container mt-5">
        {% block content %}
        <br>
        <br>
        <div class="row">
          <div class="col-6 text-right">
            <a href="{% url 'authors:list' %}" class="btn btn-primary">Authors</a>
          </div>
          <div class="col-6">
            <a href="{% url 'books:list' %}" class="btn btn-primary">Books</a>
          </div>
        </div>
        {% endblock content %}
    </div>

  {% render_bundle 'main' %}
</body>
</html>